"""add reset_password_token field to user

Revision ID: a5d24772bb18
Revises: 8e43aa2bcbb0
Create Date: 2025-12-06 20:54:10.957968

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5d24772bb18'
down_revision: Union[str, Sequence[str], None] = '8e43aa2bcbb0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('reset_password_token', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'reset_password_token')
    # ### end Alembic commands ###
