"""add role to user model

Revision ID: a621a09113d2
Revises: a5d24772bb18
Create Date: 2025-12-06 23:24:45.512442

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a621a09113d2"
down_revision: Union[str, Sequence[str], None] = "a5d24772bb18"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    userrole_enum = sa.Enum("ADMIN", "USER", name="userrole")
    userrole_enum.create(op.get_bind(), checkfirst=True)
    op.add_column(
        "users", sa.Column("role", userrole_enum, nullable=False, server_default="USER")
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "role")
    # ### end Alembic commands ###
